config/routes.rb
Clinic::Application.routes.draw do
  resources :appointments do
    collection do
      put :mark_completed
    end
  end

  devise_for :users
  resources :patients
  root :to => "patients#main_menu"

  get "/search" => 'patients#search'
  post "/search" => 'patients#search'

  get "/main_menu" => 'patients#main_menu'
  post "/main_menu" => 'patients#main_menu'

  get "/history" => 'appointments#history'
  post "/history" => 'appointments#history'
  
  get "/pdf" => 'appointments#generate_pdf'
  post "/pdf" => 'appointments#generate_pdf'

  get "/pdf2" => 'patients#generate_pdf'
  post "/pdf2" => 'patients#generate_pdf'

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	validates :name, presence: true
	validates :id_num, presence: true
	validates :cell_no, presence: true
	validates :email, presence: true, uniqueness: true
	validates :record_num, presence: true
	has_many :appointments
	before_validation :prep_email
	before_save :create_avatar_url
	
	
	def self.search(params)
    searched_name = params[:keyword].strip
    searched_name = searched_name.downcase
    if searched_name.is_integer?
      if searched_name.length > 8
        where("cell_no LIKE ?", "%#{searched_name}%")
      elsif searched_name.length <= 7
        where("record_num LIKE ?", "%#{searched_name}%")
      end
    else
      if !searched_name.include? '@'
        where("name ILIKE ?", "%#{searched_name}%") 
      else
        where("email ILIKE ?", "%#{searched_name}%")
      end
    end
    
  end

	def prep_email
		self.email = self.email.strip.downcase if self.email
	end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=200"
	end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /patients
  # GET /patients.json

  def main_menu
    @patients = Patient.all
    @appointments = Appointment.all
    @on_index_page = true
  end
  
  def generate_pdf
    id_s = params[:pati]
    id = id_s
    p = Patient.find(id)
    if p.appointments.any?
      aps = p.appointments.find(:all)
      
      def text_date(ap) #takes an appointment object as input and returns its formatted date 
        ap.appointment_date.strftime("%d/%m/%Y as %H:%M")
      end
      
      ap_list = Array.new
      if aps.any?
        ap_list << ["<font size='20'><b>Data: </b></font>", "<font size='20'>Tipo</font>", "<font size='20'>Preco</font>"]
        aps.each do |a|
          ap_list << ["<font size='20'><b>#{text_date(a)}</b></font>", "<font size='20'>Consulta</font>", "<font size='20'> #{a.price.to_s} AKz </font>"]
        end
      end
      
      
      pdf = Prawn::Document.new
      pdf.text "\n\n\n", :inline_format => true
      pdf.text "<b><i>Clinica Familiar Sol Maria</i></b>", :size => 32, :align => :center, :inline_format => true
      pdf.text "<b>www.sol-maria.com</b>", :size => 15, :align => :center, :inline_format => true
      pdf.text "<b>Tel:</b> 923-12-34-56", :size => 15, :align => :center, :inline_format => true
      pdf.text "<b>Fax:</b> 222-45-54-23", :size => 15, :align => :center, :inline_format => true
      pdf.text "\n\n\n\n", :inline_format => true
      pdf.move_down 30    
      pdf.stroke_horizontal_rule
      pdf.move_down 10    
      pdf.text "<i>HISTORICO DE CONSULTAS</i>", :size => 13, :inline_format => true, :align => :center
      pdf.text "<b>Paciente: " + p.name + "</b>", :size => 13, :inline_format => true
      pdf.text "<b>Numero de Ficheiro: " + p.record_num + "</b>", :size => 13, :inline_format => true
      pdf.stroke_horizontal_rule
      pdf.move_down 30
      pdf.text "\n\n\n", :inline_format => true
      pdf.table(ap_list, 
                   :cell_style => { :inline_format => true }, :position => :center)
      filename = File.join(Rails.root, "historico.pdf")
      pdf.render_file filename
      send_file filename, :filename => p.name + ".pdf", :type => "application/pdf"
    else
      pdf = Prawn::Document.new
      pdf.text "\n\n\n", :inline_format => true
      pdf.text "<b><i>Clinica Familiar Sol Maria</i></b>", :size => 32, :align => :center, :inline_format => true
      pdf.text "<b>www.sol-maria.com</b>", :size => 15, :align => :center, :inline_format => true
      pdf.text "<b>Tel:</b> 923-12-34-56", :size => 15, :align => :center, :inline_format => true
      pdf.text "<b>Fax:</b> 222-45-54-23", :size => 15, :align => :center, :inline_format => true
      pdf.text "\n\n\n\n", :inline_format => true
      pdf.move_down 30    
      pdf.stroke_horizontal_rule
      pdf.move_down 10    
      pdf.text "<i>HISTORICO DE CONSULTAS</i>", :size => 13, :inline_format => true, :align => :center
      pdf.text "<b>Paciente: " + p.name + "</b>", :size => 13, :inline_format => true
      pdf.text "<b>Numero de Ficheiro: " + p.record_num + "</b>", :size => 13, :inline_format => true
      pdf.stroke_horizontal_rule
      pdf.move_down 30
      pdf.text "\n\n\n", :inline_format => true
      pdf.text "<b>Este paciente nao tem consultas no historico</b>", :size => 13, :inline_format => true
      filename = File.join(Rails.root, "historico.pdf")
      pdf.render_file filename
      send_file filename, :filename => p.name + ".pdf", :type => "application/pdf"
    end
  end

  #XXX add option to generate pdf with full patient history.
  def index
    @patients = Patient.all
    @appointments = Appointment.all
    @on_index_page = true
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @appointments = @patient.appointments.find(:all)
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  def search
    @patients = Patient.search(params)
    @keyw = params[:keyword]
  end


  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Ficheiro do paciente ' + @patient.name + ' foi criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Ficheiro do paciente ' + @patient.name + ' foi editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    patient_identification = @patient.id
    @patient.destroy
    respond_to do |format|
      Appointment.destroy_all(:patient_id => patient_identification)
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :gender, :id_num, :record_num, :address, :cell_no, :email, :dob, :employer, :plan, :notes)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for (@patient) do |f| %>

      <%= f.input :name, label: "Nome", :class => 'text_field' %>

      <%= f.input :id_num, label: "B.I", :class => 'text_field' %>

      <%= f.input :record_num, label: "Numero do Ficheiro", :class => 'text_field' %>

      <%= f.input :address, label: "Endereco", :class => 'text_field' %>

      <%= f.input :cell_no, label: "Celular", :class => 'text_field' %>

      <%= f.input :email, label: "Email", :class => 'text_field' %>

      <%= f.input :dob, :as => :date, :start_year => Date.today.year - 5,
                                      :end_year => 1920,
                  :order => [ :day, :month, :year], :required => true, label: "Data de Nascimento", :class => 'text_field' %>

      <%= f.input :employer, label: "Local de Emprego", :class => 'text_field' %>

      <%= f.input :plan, label: "Plano de Saude", :class => 'text_field' %>

      <%= f.input :notes, label: "Anotacoes", :class => 'text_field' %>

      <%= f.button :submit, :class=> 'btn btn-warning', :value => "Salvar" %>
      
    <%= link_to "Cancelar",
                patients_path, :class => 'btn btn' %>
<% end %>

app/views/patients/_patient.html.erb
<li>
	<%= link_to patient.name, patient_path(patient) %>
</li>

app/views/patients/edit.html.erb
<%- model_class = Patient -%>
  <legend>Editar Ficheiro de Paciente</legend>
<%= render :partial => 'form' %>

app/views/patients/index.html.erb
<%- model_class = Patient -%>
    <legend>Pacientes</legend>
<% if !(@patients.empty?) %>
<%= form_tag(search_path, method: 'get') do %>
<p>
  <strong>Procurar Ficheiro:  </strong><%= text_field_tag :keyword %>
</p>
<% end %>
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th><b>Ficheiro</b></th>
      <th><b>Nome</b></th>
      <th class="hidden-phone"><b>Ficheiro numero</b></th>
      <th><b>Celular</b></th>
      <th class="hidden-phone"><b>Data de Nascimento</b></th>
      <th class="hidden-phone"></th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to "Ver", patient_path(patient),
            :class => 'btn btn-mini btn-success' %></td>
        <td><%= patient.name %></td>
        <td class="hidden-phone"><%= patient.record_num %></td>
        <td><%= patient.cell_no %></td>
        <td class="hidden-phone"><%= patient.dob.strftime("%d/%m/%Y") %></td>
        <td class="hidden-phone">
          <%= link_to "Editar",
                      edit_patient_path(patient), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to "Adicionar",
            new_patient_path,
            :class => 'btn btn-warning' %>

app/views/patients/main_menu.html.erb
<legend>Menu Principal</legend>
<div class="span3">
</div>
<div class="span2">
<%= link_to "Adicionar Paciente",
            new_patient_path,
            :class => 'btn btn-block' %>
            <br />
<%= link_to "Marcar Consulta",
            new_appointment_path,
            :class => 'btn btn-block' %>
            <br />
<%= link_to "Ver Pacientes", patients_path,
            :class => 'btn btn-block' %>
            <br />
<%= link_to "Ver Consultas", appointments_path,
            :class => 'btn btn-block' %>
            <br />
<%= link_to "Ver Historico", history_path,
            :class => 'btn btn-block' %>
</div>

app/views/patients/new.html.erb
<%- model_class = Patient -%>
  <legend>Novo Paciente</legend>
<%= render :partial => 'form' %>

app/views/patients/search.html.erb
<legend>Resultados da Pesquisa</legend>

<% if @patients %>
<% if @patients.any? %>
	<table class="table table-striped table-bordered table-hover table-condensed">
  		<thead>
    		<tr>
      			<th><b>Ficheiro</b></th>
      			<th><b>Nome</b></th>
      			<th><b>Ficheiro numero</b></th>
      			<th><b>Celular</b></th>
      			<th><b>Data de Nascimento</b></th>
      			<th></th>
    		</tr>
  		</thead>
  		<tbody>
    		<% @patients.each do |patient| %>
      			<tr>
        			<td><%= link_to "Ver", patient_path(patient),
            			:class => 'btn btn-mini btn-success' %></td>
        			<td><%= patient.name %></td>
        			<td><%= patient.record_num %></td>
        			<td><%= patient.cell_no %></td>
        			<td><%= patient.dob.strftime("%d/%m/%Y") %></td>
        			<td>
          				<%= link_to "Editar",
                      		edit_patient_path(patient), :class => 'btn btn-mini' %>
          				<%= link_to "Eliminar",
		                      patient_path(patient),
		                      :method => :delete,
		                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		                      :class => 'btn btn-mini btn-danger' %>
        			</td>
      			</tr>
    		<% end %>
  		</tbody>
	</table>
	<%= link_to "Voltar",
              patients_path, :class => 'btn'  %>
<% else %>
	<p>Nao foi encontrado nenhum paciente com nome de <%= @keyw %>.</p>
	<p>Tente uma pesquisa diferente:</p>
	<%= form_tag(search_path, method: 'get') do %>
		<p>
  			<%= text_field_tag :keyword %>
		</p>
	<% end %>
	<%= link_to "Voltar",
              patients_path, :class => 'btn'  %>
<% end %>
<% end %>

app/views/patients/show.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <legend>Ficheiro de <%= @patient.name %></legend>
</div>
<div class="row">
<div class="span5">
<dl class="dl-horizontal">
  <dt><strong>B.I.:</strong></dt>
  <dd><%= @patient.id_num %></dd>
  <dt><strong>Numero (Ficheiro):</strong></dt>
  <dd><%= @patient.record_num %></dd>
  <dt><strong>Endereco:</strong></dt>
  <dd><%= @patient.address %></dd>
  <dt><strong>Celular:</strong></dt>
  <dd><%= @patient.cell_no %></dd>
  <dt><strong>Email:</strong></dt>
  <dd><%= @patient.email %></dd>
  <dt><strong>Data Nascimento:</strong></dt>
  <dd><%= @patient.dob %></dd>
  <dt><strong>Local de Emprego:</strong></dt>
  <dd><%= @patient.employer %></dd>
  <dt><strong>Plano de Saude:</strong></dt>
  <dd><%= @patient.plan %></dd>
</dl>
</div>
<div class="span2">
  <img class="avatar" src="<%= @patient.avatar_url %>" />
</div> 
</div>
<strong>Historico e anotacoes:</strong>
  <%= simple_format(@patient.notes) %>
<div class="form-actions">
  <%= link_to "Voltar ao indice",
              patients_path, :class => 'btn'  %>
  <%= link_to "Editar",
              edit_patient_path(@patient), :class => 'btn', :value => "Editar" %>
  <%= link_to "Apagar",
              patient_path(@patient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% if @patient.appointments.any? %>
    <%= link_to "Imprimir Historico", pdf2_path(:pati => @patient.id.to_s), :class => 'btn btn-warning' %>
  <% else %>
    <%= link_to "Imprimir Detalhes", pdf2_path(:pati => @patient.id.to_s), :class => 'btn btn-warning' %>
  <% end %>
</div>
<% if @appointments.any? %>
   <h4>Este paciente tem <%= @appointments.count %>
    <% if @appointments.count == 1 %>
      consulta
    <% else %>
      consultas
    <% end %>
    no Historico</h4>
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr>
        <th><b>Ficheiro</b></th>
        <th><b>Detalhes</b></th>
        <th><b>Data Marcada</b></th>
        <th><b>Consulta Efectuada</b></th>
      </tr>
    </thead>
    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
            <td><%= link_to "Ver", appointment_path(appointment), :class => 'btn btn-success' %></td>
          <td><%= appointment.details %></td>
          <td><%= appointment.appointment_date.strftime("%d/%m/%Y %H:%M") %></td>
          <td><%= (appointment.completed == 1) ? 'Sim' : 'Nao' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% end %>