config/routes.rb
Clinic::Application.routes.draw do
  resources :appointments do
    collection do
      put :mark_completed
    end
  end

  devise_for :users
  resources :patients
  root :to => "patients#main_menu"

  get "/search" => 'patients#search'
  post "/search" => 'patients#search'

  get "/main_menu" => 'patients#main_menu'
  post "/main_menu" => 'patients#main_menu'

  get "/history" => 'appointments#history'
  post "/history" => 'appointments#history'
  
  get "/pdf" => 'appointments#generate_pdf'
  post "/pdf" => 'appointments#generate_pdf'

  get "/pdf2" => 'patients#generate_pdf'
  post "/pdf2" => 'patients#generate_pdf'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  
  def self.get_archived
        where("archived = ?", 1)
  end
  
  def self.get_non_archived
        where("archived = ?", 0)
  end

  def self.get_completed
        where("completed = ?", 1)
  end

  def self.get_incomplete
        where("completed = ?", 0)
  end
	validates :patient_id, presence: true, length: { minimum: 1 }
	validates :appointment_date, presence: true
	validates :price, presence: true
	belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	validates :name, presence: true
	validates :id_num, presence: true
	validates :cell_no, presence: true
	validates :email, presence: true, uniqueness: true
	validates :record_num, presence: true
	has_many :appointments
	before_validation :prep_email
	before_save :create_avatar_url
	
	
	def self.search(params)
    searched_name = params[:keyword].strip
    searched_name = searched_name.downcase
    if searched_name.is_integer?
      if searched_name.length > 8
        where("cell_no LIKE ?", "%#{searched_name}%")
      elsif searched_name.length <= 7
        where("record_num LIKE ?", "%#{searched_name}%")
      end
    else
      if !searched_name.include? '@'
        where("name ILIKE ?", "%#{searched_name}%") 
      else
        where("email ILIKE ?", "%#{searched_name}%")
      end
    end
    
  end

	def prep_email
		self.email = self.email.strip.downcase if self.email
	end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=200"
	end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def generate_pdf
    id_s = params[:appo]
    id = id_s
    appointment = Appointment.find(id)
    patient = Patient.find(appointment.patient_id)
    text_date = appointment.appointment_date.strftime("%d/%m/%Y as %H:%M")
    pdf = Prawn::Document.new
    pdf.text "\n\n\n", :inline_format => true
    pdf.text "<b><i>Clinica Familiar Sol Maria</i></b>", :size => 32, :align => :center, :inline_format => true
    pdf.text "<b>www.sol-maria.com</b>", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Tel:</b> 923-12-34-56", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Fax:</b> 222-45-54-23", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Endereco:</b>", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Rua </b>XYZ", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Bloco</b> HJK", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Casa</b> 123", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Horario de atendimento:</b>", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Seg-Sex</b> - das 09:00 as 18:00", :size => 15, :align => :center, :inline_format => true
    pdf.text "<b>Sabado</b> - das 09:00 as 13:00", :size => 15, :align => :center, :inline_format => true
    pdf.text "\n\n\n\n", :inline_format => true
    pdf.move_down 30    
    pdf.stroke_horizontal_rule
    pdf.move_down 10    
    pdf.text "<i>RECIBO DE CONSULTA</i>", :size => 13, :inline_format => true, :align => :center
    pdf.stroke_horizontal_rule
    pdf.move_down 30
    pdf.text "\n\n\n", :inline_format => true
    pdf.table([  ["<font size='20'><b>Paciente: </b></font>", "<font size='20'><i>" + patient.name + "</i></font>"],
                 ["<font size='20'><b>Data Marcada: </b></font>", "<font size='20'><i>" + text_date + "</i></font>"],
                 ["<font size='20'><b>Preco da Consulta: </b></font>", "<font size='20'><i>" + appointment.price.to_s + " AKZ" + "</i></font>"] ], 
                 :cell_style => { :inline_format => true }, :position => :center)
    filename = File.join(Rails.root, "recibo.pdf")
    pdf.render_file filename
    send_file filename, :filename => patient.name + ".pdf", :type => "application/pdf"
  end
  
  def index
    @appointments = Appointment.get_incomplete.order("appointment_date desc")
    @patients = Patient.all
    @on_index_page = true
  end

  def history
    @appointments = Appointment.all.get_completed.order("appointment_date desc")
    @patients = Patient.all
  end

  # GET /appointments/1
  # GET /appointments/1.json

  #XXX Define tags that can be associated with consultations- - to allow to search by keyword.
  def show
    @patients = Patient.all
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @patients = Patient.all
  end

  def mark_completed
    Appointment.update_all({completed: 1}, {id: params[:appointment_ids]})
    redirect_to appointments_url
  end

  # GET /appointments/1/edit
  def edit
    @patients = Patient.all
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @patients = Patient.all
    
    respond_to do |format|
      if @appointment.save
         #nexmo = Nexmo::Client.new('62c6f18a', '1aeaa866')
         #sms_text = ("Consulta de " + @patients.find(@appointment.patient_id).name)
         #sms_text = sms_text + " foi marcada para " + appointment_params[:"appointment_date(3i)"]
         #sms_text = sms_text + " de " + appointment_params[:"appointment_date(2i)"]
         #sms_text = sms_text + " de " + appointment_params[:"appointment_date(1i)"]
          #nexmo.send_message!({:to => '27760714429', :from =>  'Ruby', :text => sms_text})
        format.html { redirect_to @appointment, notice: 'Consulta do paciente ' + @patients.find(@appointment.patient_id).name + ' foi criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    @patients = Patient.all
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Consulta do paciente ' + @patients.find(@appointment.patient_id).name + ' foi editada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :details, :appointment_date, :special_supplies, :completed, :price)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
	def appointments_chart_data
		(6.months.ago.to_date..Date.today).map do |date|
			{
				appointment_date: date,
				price: Appointment.where("date(appointment_date) = ?", date).sum(1)
			}
		end
	end
end

app/views/appointments/_form.html.erb
<%= simple_form_for (@appointment) do |f| %>

      <%= f.input :patient_id, collection: @patients, :label => "Paciente" %>

      <%= f.input :details, :label => "Detalhes", :class => 'text_field' %>

      <%= f.input :appointment_date, :label => "Data da Consulta", :as => :datetime %>

      <%= f.input :price, :label => "Preco da Consulta", :class => 'text_field' %>

      <%= f.input :special_supplies, :label => "Requerimentos Especiais", :class => 'text_field' %>
		
	  <% 1.times do %>
	      <% if @appointment && @appointment.completed == 1 %>
	        <% sel = '1' %>
	      <% else %>
	        <% sel = '0' %>
	      <% end %>
	      <%= f.input :completed, :collection => [['Nao',0],['Sim',1]], :label => "Esta consulta ja foi Efectuada?", :selected => sel %>
      	  
      	  <% if @appointment && @appointment.archived == 1 %>
      	  	<% sell = '1' %>
	      <% else %>
	        <% sell = '0' %>
	      <% end %>
	      	<% if @appointment.completed == 1%>
  				<%= f.input :archived, :collection => [['Nao',0],['Sim',1]], :label => "Arquivar consulta", :selected => sell %>
  			<% end %>
  		<% end %>
      
      
      	
      

    <%= f.button :submit, :class => 'btn btn-warning', :value => "Salvar" %>
    <%= link_to "Cancelar",
                appointments_path, :class => 'btn' %>
<% end %>

app/views/appointments/edit.html.erb
<%- model_class = Appointment -%>
  <legend>Editar detalhes da Consulta</legend>
<%= render :partial => 'form' %>

app/views/appointments/history.html.erb
<%- model_class = Appointment -%>
<legend>Historico de Consultas</legend>
<% if !(@appointments.empty?) %>
<%= content_tag :div, "", id: "appointments_chart", data: {appointments: appointments_chart_data}, :class => "hidden-phone" %>
<% end %>

<% if !(@patients.empty?) %>
<% if !(@appointments.empty?) %>

<%= form_tag mark_completed_appointments_path, method: :put do %>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <tr>
      
  <th><b></b></th>
<% end %>
      <th><b>Ficheiro</b></th>
      <th><b>Paciente</b></th>
      <th class="hidden-phone"><b>Detalhes</b></th>
      <th><b>Data Marcada</b></th>
      <th class="hidden-phone"><b>Requerimentos Especiais</b></th>
      <th class="hidden-phone"><b>Consulta Efectuada</b></th>
      <th class="hidden-phone"></th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <% if !(@appointments.empty?) %>
  <td><%= check_box_tag "appointment_ids[]", appointment.id %></td>
<% end %>
        <td><%= link_to "Ver", appointment_path(appointment), :class => 'btn btn-success' %></td>
        <td><%= @patients.find(appointment.patient_id).name %></td>
        <td class="hidden-phone"><%= appointment.details %></td>
        <td><%= appointment.appointment_date.strftime("%d/%m/%Y") %></td>
        <td class="hidden-phone"><%= appointment.special_supplies %></td>
        <td class="hidden-phone"><%= (appointment.completed == 1) ? 'Sim' : 'Nao' %></td>
        <td class="hidden-phone">
          <%= link_to "Editar",
                      edit_appointment_path(appointment), :class => 'btn btn-mini' %></td>
        <td class="hidden-phone">
          <%= link_to "Eliminar",
                      appointment_path(appointment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% else %>
  <h2>Precisa adicionar Pacientes antes de poder ver o historico</h2>
<% end %>

app/views/appointments/index.html.erb
<%- model_class = Appointment -%>
<legend>Consultas</legend>
<% if !(@patients.empty?) %>
<% if !(@appointments.empty?) %>
<%= form_tag mark_completed_appointments_path, method: :put do %>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <tr>
      
  <th><b></b></th>
<% end %>
      <th><b>Ficheiro</b></th>
      <th><b>Paciente</b></th>
      <th class="hidden-phone"><b>Detalhes</b></th>
      <th><b>Data Marcada</b></th>
      <th class="hidden-phone"><b>Requerimentos Especiais</b></th>
      <th class="hidden-phone"><b>Consulta Efectuada</b></th>
      <th class="hidden-phone"></th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <% if !(@appointments.empty?) %>
  <td><%= check_box_tag "appointment_ids[]", appointment.id %></td>
<% end %>
        <td><%= link_to "Ver", appointment_path(appointment), :class => 'btn btn-success' %></td>
        <td><%= @patients.find(appointment.patient_id).name %></td>
        <td class="hidden-phone"><%= appointment.details %></td>
        <td><%= appointment.appointment_date.strftime("%d/%m/%Y") %></td>
        <td class="hidden-phone"><%= appointment.special_supplies %></td>
        <td class="hidden-phone"><%= (appointment.completed == 1) ? 'Sim' : 'Nao' %></td>
        <td class="hidden-phone">
          <%= link_to "Editar",
                      edit_appointment_path(appointment), :class => 'btn btn-mini' %></td>
        <td class="hidden-phone">
          <%= link_to "Eliminar",
                      appointment_path(appointment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if !(@appointments.empty?) %>
  <%= submit_tag "Marcar Como Efectuada",
            :class => 'btn btn-default' %>
<% end %>
<% end %>

<% else %>
  <p>Precisa adicionar Pacientes antes de usar este menu</p>
<% end %>


<%= link_to "Programar Nova Consulta",
            new_appointment_path,
            :class => 'btn btn-warning' %>

app/views/appointments/new.html.erb
<%- model_class = Appointment -%>
  <legend>Nova Consulta</legend>

<% if !(@patients.empty?) %>
	<%= render :partial => 'form' %>
<% else %>
	<h3>Precisa adicionar o Paciente antes de poder marcar uma consulta</h3>
<% end %>

app/views/appointments/show.html.erb
<%- model_class = Appointment -%>
  <legend>Consulta</legend>

<dl class="dl-horizontal">
  <dt><strong>Nome do Paciente:</strong></dt>
  <dd><%= @patients.find(@appointment.patient_id).name %></dd>
  <dt><strong>Data Marcada:</strong></dt>
  <dd><%= @appointment.appointment_date %></dd>
  <dt><strong> Preco:</strong></dt>
  <dd><%= @appointment.price %> AKz</dd>
  <dt><strong>Detalhes:</strong></dt>
  <dd><%= @appointment.details %></dd>
</dl>
<% if @appointment.completed == 1 %>
  	<div class="well"><p class="text-success"><strong> Esta consulta ja foi efectuada.</strong></p></div>
  <% end %>
<% if @appointment.archived == 1 %>
  	<div class="well"><p class="text-success"><strong> Esta consulta esta arquivada.</strong></p></div>
  <% end %>

<div class="form-actions">
  <%= link_to "Voltar",
              appointments_path, :class => 'btn'  %>
  <%= link_to "Editar",
              edit_appointment_path(@appointment), :class => 'btn' %>
  <%= link_to "Apagar",
              appointment_path(@appointment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <%= link_to "Imprimir Recibo", pdf_path(:appo => @appointment.id.to_s), :class => 'btn btn-warning' %>
</div>