config/routes.rb
Clinic::Application.routes.draw do
  resources :appointments do
    collection do
      put :mark_completed
    end
  end

  devise_for :users
  resources :patients
  root :to => "patients#main_menu"

  get "/search" => 'patients#search'
  post "/search" => 'patients#search'

  get "/main_menu" => 'patients#main_menu'
  post "/main_menu" => 'patients#main_menu'

  get "/history" => 'appointments#history'
  post "/history" => 'appointments#history'
  
  get "/pdf" => 'appointments#generate_pdf'
  post "/pdf" => 'appointments#generate_pdf'

  get "/pdf2" => 'patients#generate_pdf'
  post "/pdf2" => 'patients#generate_pdf'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Sacramento' rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sol Maria" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <style type="text/css">
        body {
          padding-bottom: 80px;
          color: #5b5b5b;
        }
    </style>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand navbar-link" href="#"><i class="glyphicon icon-plus icon-white"></i>  Clinica Familiar <span class = "solmaria">Sol Maria</span></a>
            <div class="container nav-collapse">
              <ul class="nav navbar-left pull-left ">
                <% if user_signed_in? %>
                <li class="divider-vertical"></li>
                <li><%= link_to "Menu", main_menu_path  %></li>
                <li><%= link_to "Pacientes", patients_path  %></li>
                <li><%= link_to "Consultas", appointments_path  %></li>
                <li><%= link_to "Historico", history_path  %></li>
               <li class="divider-vertical"></li>
              </li>
                <% end %>
              </ul>
              <ul class="nav pull-right navbar-right">
                <% if user_signed_in? %>
                  <li class='pull-right navbar-right'>
                    <%= link_to "Utilizador: #{current_user.email} ", edit_user_registration_path %>
                  </li>
                  <li class="divider-vertical"></li>
                  <li class='pull-right navbar-right'>
                    <%= link_to "Sair", destroy_user_session_path, method: "delete" %>
                  </li>
                  <% else %>
                  <li class="divider-vertical"></li>
                  <li class='pull-right navbar-right'>
                    <%= link_to "Iniciar Sessao", new_user_session_path %>
                  </li>
              <% end %>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <div class="well">
              <fieldset>
            <%= yield %>
            </fieldset>
            </div>
          </div>
          <% if @on_index_page %>
          <div class="span3">
            <div class="well sidebar-nav pull-right">
              <div id="clinic_alerts">
                <legend>Mensagens</legend>
                <% 1.times do %>
                  <% error_counter = 0 %>
                    <% @appointments.each do |ap| %>
                      <% if ap.completed == 0 %>
                        <% if ap.appointment_date < (DateTime.now) %>
                          <% error_counter = error_counter + 1 %>
                          <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            A consulta de <%= @patients.find(ap.patient_id).name %> passou!
                          </div>
                        <% elsif DateTime.now <= ap.appointment_date + 6.hours %>
                          <% error_counter = error_counter + 1 %>
                          <div class="alert alert-warning alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            A consulta de <%= @patients.find(ap.patient_id).name %> esta marcada para dentro em breve!
                          </div>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% if error_counter == 0 %>
                      <div class="alert alert-success">
                        Nao tem consultas marcadas para hoje!
                      </div>
                    <% end %>
                <% end %>
            </div><!--/.well -->
          </div><!--/span-->
           <% end %>
        </div><!--/row-->
      <br />
      <br />
      <br />
    </div> <!-- /container -->
<!-- FOOTER -->
    <nav id="footbar" class="navbar navbar-fixed-bottom" role="navigation" >
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-inner">
    <div class="nav navbar-nav pull-right navbar-right">
      <ul class="nav">  
      <li><a href="http://wilsonmaravilha.com">&copy; Wilson Maravilha - <%= Date.today.year %></a></li>
      <li class="divider-vertical"></li>
      <li><a href="http://wilsonmaravilha.com/contacto-sol-maria/" target="_blank" >Suporte Tecnico</a></li>
    </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>
  </body>
</html>